Repository IIIIBarcode/weather-wear, pull requests merged in 2023-09, with the labels that each got.

#4 [feat] 탭바구현, 메인페이지에서 피드백 페이지 이동 버튼 추가
  FeedbackViewController.swift
  WeatherWear.xcodeproj/project.pbxproj
  WeatherWear/Main/ViewController.swift
  WeatherWear/Source/SceneDelegate.swift
  WeatherWear/TapbarController.swift
  WeatherWear/WeeklyWear/WeeklyWearViewController.swift
Labels: FEATURE

#7 [bug] 네비게이션바 위치가 아래로 내려가 있는 버그 수정
  WeatherWear/Source/SceneDelegate.swift
Labels: FIX

#15 [ui] 메인페이지: 상단부 ui 구현
  WeatherWear/Assets.xcassets/TodayPage Icon/Contents.json
  WeatherWear/Assets.xcassets/TodayPage Icon/gpsIcon.imageset/Contents.json
  WeatherWear/Assets.xcassets/TodayPage Icon/gpsIcon.imageset/gpsIcon.png
  WeatherWear/Assets.xcassets/Weather Icon/Contents.json
  WeatherWear/Assets.xcassets/Weather Icon/rainIcon.imageset/Contents.json
  WeatherWear/Assets.xcassets/Weather Icon/rainIcon.imageset/rainIcon.png
  WeatherWear/Assets.xcassets/backgroundSample.imageset/Contents.json
  WeatherWear/Assets.xcassets/backgroundSample.imageset/backgroundSample.png
  WeatherWear/Main/ViewController.swift
Labels: UI

#17 [ui] 메인페이지: 피드백 페이지로 가는 버튼 추가
  WeatherWear/Main/ViewController.swift
Labels: FEATURE

#18 [ui] 주간옷추천 페이지 ui구현
  WeatherWear.xcodeproj/project.pbxproj
  WeatherWear/Assets.xcassets/myLocation.imageset/Contents.json
  WeatherWear/Assets.xcassets/myLocation.imageset/fluent_my-location-24-filled.png
  WeatherWear/Assets.xcassets/weather/Contents.json
  WeatherWear/Assets.xcassets/weather/am.imageset/Contents.json
  WeatherWear/Assets.xcassets/weather/am.imageset/ph_sun-fill.png
  WeatherWear/Assets.xcassets/weather/pm.imageset/Contents.json
  WeatherWear/Assets.xcassets/weather/pm.imageset/ph_sun-fill (1).png
  WeatherWear/Assets.xcassets/weather/rain.imageset/Contents.json
  WeatherWear/Assets.xcassets/weather/rain.imageset/carbon_rain.png
  WeatherWear/WeeklyWear/WeeklyTableViewCell.swift
  WeatherWear/WeeklyWear/WeeklyWearViewController.swift
Labels: UI

#23 [fix] 세그먼트컨트롤 텍스트 수정, 서치바 위치 변경, 테이블뷰 클릭 이벤트 제거
  WeatherWear/WeeklyWear/WeeklyWearViewController.swift
Labels: FIX
